package com.faprayyy.tonton.utils

import com.faprayyy.tonton.data.local.entity.FavoriteEntity
import com.faprayyy.tonton.data.local.entity.MovieEntity
import com.faprayyy.tonton.data.local.entity.SeriesEntity
import com.faprayyy.tonton.data.remote.response.*
import com.faprayyy.tonton.view.ui.detail.detailmovie.DetailMovieActivity.Companion.MOVIE_TYPE
import com.faprayyy.tonton.view.ui.detail.detailseries.DetailSeriesActivity.Companion.SERIES_TYPE
import com.google.gson.Gson

object DataDummy{
    private const val stringListMovieResponse = "{\"page\":1,\"results\":[" +
            "{\"adult\":false,\"backdrop_path\":\"/fPGeS6jgdLovQAKunNHX8l0avCy.jpg\",\"genre_ids\":[28,12,53,10752],\"id\":567189,\"original_language\":\"en\",\"original_title\":\"Tom Clancy's Without Remorse\",\"overview\":\"An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.\",\"popularity\":3143.69,\"poster_path\":\"/rEm96ib0sPiZBADNKBHKBv5bve9.jpg\",\"release_date\":\"2021-04-29\",\"title\":\"Tom Clancy's Without Remorse\",\"video\":false,\"vote_average\":7.3,\"vote_count\":876}," +
            "{\"adult\":false,\"backdrop_path\":\"/6ELCZlTA5lGUops70hKdB83WJxH.jpg\",\"genre_ids\":[28,14,12],\"id\":460465,\"original_language\":\"en\",\"original_title\":\"Mortal Kombat\",\"overview\":\"Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.\",\"popularity\":2681.013,\"poster_path\":\"/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg\",\"release_date\":\"2021-04-07\",\"title\":\"Mortal Kombat\",\"video\":false,\"vote_average\":7.6,\"vote_count\":2482}," +
            "{\"adult\":false,\"backdrop_path\":\"/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg\",\"genre_ids\":[28,53,80,35],\"id\":615457,\"original_language\":\"en\",\"original_title\":\"Nobody\",\"overview\":\"Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a \\\"nobody.\\\" When two thieves break into his home one night, Hutch's unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.\",\"popularity\":1602.076,\"poster_path\":\"/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg\",\"release_date\":\"2021-03-26\",\"title\":\"Nobody\",\"video\":false,\"vote_average\":8.4,\"vote_count\":1483}," +
            "{\"adult\":false,\"backdrop_path\":\"/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg\",\"genre_ids\":[878,28,18],\"id\":399566,\"original_language\":\"en\",\"original_title\":\"Godzilla vs. Kong\",\"overview\":\"In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.\",\"popularity\":1658.18,\"poster_path\":\"/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg\",\"release_date\":\"2021-03-24\",\"title\":\"Godzilla vs. Kong\",\"video\":false,\"vote_average\":8.1,\"vote_count\":5505}," +
            "{\"adult\":false,\"backdrop_path\":\"/n2y7T8wJVjJ8yLhQXQgNCpsC3ga.jpg\",\"genre_ids\":[10751,16,35],\"id\":811367,\"original_language\":\"en\",\"original_title\":\"22 vs. Earth\",\"overview\":\"Set before the events of ‘Soul’, 22 refuses to go to Earth, enlisting a gang of 5 new souls in attempt of rebellion. However, 22’s subversive plot leads to a surprising revelation about the meaning of life.\",\"popularity\":1299.426,\"poster_path\":\"/32vLDKSzcCMh55zqqaSqqUA8naz.jpg\",\"release_date\":\"2021-04-30\",\"title\":\"22 vs. Earth\",\"video\":false,\"vote_average\":7.2,\"vote_count\":72}," +
            "{\"adult\":false,\"backdrop_path\":\"/lkInRiMtLgl9u9xE0By5hqf66K8.jpg\",\"genre_ids\":[27],\"id\":632357,\"original_language\":\"en\",\"original_title\":\"The Unholy\",\"overview\":\"Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.\",\"popularity\":1165.637,\"poster_path\":\"/b4gYVcl8pParX8AjkN90iQrWrWO.jpg\",\"release_date\":\"2021-03-31\",\"title\":\"The Unholy\",\"video\":false,\"vote_average\":5.6,\"vote_count\":86}," +
            "{\"adult\":false,\"backdrop_path\":\"/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg\",\"genre_ids\":[28,12,14,878],\"id\":791373,\"original_language\":\"en\",\"original_title\":\"Zack Snyder's Justice League\",\"overview\":\"Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.\",\"popularity\":1045.51,\"poster_path\":\"/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg\",\"release_date\":\"2021-03-18\",\"title\":\"Zack Snyder's Justice League\",\"video\":false,\"vote_average\":8.5,\"vote_count\":5445}," +
            "{\"adult\":false,\"backdrop_path\":\"/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg\",\"genre_ids\":[16,28,12,14,18],\"id\":635302,\"original_language\":\"ja\",\"original_title\":\"劇場版「鬼滅の刃」無限列車編\",\"overview\":\"Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!\",\"popularity\":1058.705,\"poster_path\":\"/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg\",\"release_date\":\"2020-10-16\",\"title\":\"Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train\",\"video\":false,\"vote_average\":8.4,\"vote_count\":948}," +
            "{\"adult\":false,\"backdrop_path\":\"/lHhc60NXYzswU4TvKSo45nY9Jzs.jpg\",\"genre_ids\":[16,35,10751,12],\"id\":726684,\"original_language\":\"fr\",\"original_title\":\"Miraculous World Shanghai, la légende de Ladydragon\",\"overview\":\"To join Adrien in Shanghai, Marinette is going to visit her uncle Wang who is celebrating his anniversary. But, as soon as she arrives in China, her purse gets stolen with Tikki inside, whom she needs to secretly transform into Ladybug! Without money and alone in the immense city, Marinette accepts the help of a young and resourceful girl, Fei. The two girls will ally and discover the existence of a new magical jewel, the Prodigious. Hawk Moth, also present in Shanghai, seeks to finding it since a long time...\",\"popularity\":1044.088,\"poster_path\":\"/msI5a9TPnepx47JUb2vl88hb80R.jpg\",\"release_date\":\"2021-04-04\",\"title\":\"Miraculous World: Shanghai – The Legend of Ladydragon\",\"video\":false,\"vote_average\":7.9,\"vote_count\":305}," +
            "{\"adult\":false,\"backdrop_path\":\"/7prYzufdIOy1KCTZKVWpjBFqqNr.jpg\",\"genre_ids\":[16,12,14,10751,28],\"id\":527774,\"original_language\":\"en\",\"original_title\":\"Raya and the Last Dragon\",\"overview\":\"Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.\",\"popularity\":968.182,\"poster_path\":\"/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg\",\"release_date\":\"2021-03-03\",\"title\":\"Raya and the Last Dragon\",\"video\":false,\"vote_average\":8.2,\"vote_count\":2807}," +
            "{\"adult\":false,\"backdrop_path\":\"/5Zv5KmgZzdIvXz2KC3n0MyecSNL.jpg\",\"genre_ids\":[28,53,80],\"id\":634528,\"original_language\":\"en\",\"original_title\":\"The Marksman\",\"overview\":\"Jim Hanson’s quiet life is suddenly disturbed by two people crossing the US/Mexico border – a woman and her young son – desperate to flee a Mexican cartel. After a shootout leaves the mother dead, Jim becomes the boy’s reluctant defender. He embraces his role as Miguel’s protector and will stop at nothing to get him to safety, as they go on the run from the relentless assassins.\",\"popularity\":779.143,\"poster_path\":\"/6vcDalR50RWa309vBH1NLmG2rjQ.jpg\",\"release_date\":\"2021-01-15\",\"title\":\"The Marksman\",\"video\":false,\"vote_average\":7.4,\"vote_count\":458}," +
            "{\"adult\":false,\"backdrop_path\":\"/jFINtstDUh0vHOGImpMAmLrPcXy.jpg\",\"genre_ids\":[28,27,35],\"id\":643586,\"original_language\":\"en\",\"original_title\":\"Willy's Wonderland\",\"overview\":\"When his car breaks down, a quiet loner agrees to clean an abandoned family fun center in exchange for repairs. He soon finds himself waging war against possessed animatronic mascots while trapped inside Willy's Wonderland.\",\"popularity\":871.168,\"poster_path\":\"/keEnkeAvifw8NSEC4f6WsqeLJgF.jpg\",\"release_date\":\"2021-02-12\",\"title\":\"Willy's Wonderland\",\"video\":false,\"vote_average\":6.8,\"vote_count\":210}," +
            "{\"adult\":false,\"backdrop_path\":\"/c7dFSqZQYqNNJVpacpIGZe3gkLW.jpg\",\"genre_ids\":[16,35,14],\"id\":813258,\"original_language\":\"en\",\"original_title\":\"Monster Pets: A Hotel Transylvania Short\",\"overview\":\"Drac tries out some new monster pets to help occupy Tinkles for playtime.\",\"popularity\":927.399,\"poster_path\":\"/dkokENeY5Ka30BFgWAqk14mbnGs.jpg\",\"release_date\":\"2021-04-02\",\"title\":\"Monster Pets: A Hotel Transylvania Short\",\"video\":false,\"vote_average\":7.7,\"vote_count\":108}," +
            "{\"adult\":false,\"backdrop_path\":\"/z7HLq35df6ZpRxdMAE0qE3Ge4SJ.jpg\",\"genre_ids\":[28,12,35,14],\"id\":615678,\"original_language\":\"en\",\"original_title\":\"Thunder Force\",\"overview\":\"In a world where supervillains are commonplace, two estranged childhood best friends reunite after one devises a treatment that gives them powers to protect their city.\",\"popularity\":710.121,\"poster_path\":\"/3mKMWP5OokB7QpcOMA1yl8BXFAF.jpg\",\"release_date\":\"2021-04-09\",\"title\":\"Thunder Force\",\"video\":false,\"vote_average\":5.8,\"vote_count\":569}," +
            "{\"adult\":false,\"backdrop_path\":\"/mYM8x2Atv4MaLulaV0KVJWI1Djv.jpg\",\"genre_ids\":[28,80,53],\"id\":804435,\"original_language\":\"en\",\"original_title\":\"Vanquish\",\"overview\":\"Victoria is a young mother trying to put her dark past as a Russian drug courier behind her, but retired cop Damon forces Victoria to do his bidding by holding her daughter hostage. Now, Victoria must use guns, guts and a motorcycle to take out a series of violent gangsters—or she may never see her child again.\",\"popularity\":885.067,\"poster_path\":\"/AoWY1gkcNzabh229Icboa1Ff0BM.jpg\",\"release_date\":\"2021-04-16\",\"title\":\"Vanquish\",\"video\":false,\"vote_average\":6.4,\"vote_count\":86}," +
            "{\"adult\":false,\"backdrop_path\":\"/ovggmAOu1IbPGTQE8lg4lBasNC7.jpg\",\"genre_ids\":[878,28,12,53],\"id\":412656,\"original_language\":\"en\",\"original_title\":\"Chaos Walking\",\"overview\":\"Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.\",\"popularity\":656.066,\"poster_path\":\"/9kg73Mg8WJKlB9Y2SAJzeDKAnuB.jpg\",\"release_date\":\"2021-02-24\",\"title\":\"Chaos Walking\",\"video\":false,\"vote_average\":7.2,\"vote_count\":578}," +
            "{\"adult\":false,\"backdrop_path\":\"/z8TvnEVRenMSTemxYZwLGqFofgF.jpg\",\"genre_ids\":[14,28,12],\"id\":458576,\"original_language\":\"en\",\"original_title\":\"Monster Hunter\",\"overview\":\"A portal transports Cpt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.\",\"popularity\":578.984,\"poster_path\":\"/1UCOF11QCw8kcqvce8LKOO6pimh.jpg\",\"release_date\":\"2020-12-03\",\"title\":\"Monster Hunter\",\"video\":false,\"vote_average\":7.1,\"vote_count\":1640}," +
            "{\"adult\":false,\"backdrop_path\":\"/eTgQlyIQH0nA5BsmYpvCzSPAorg.jpg\",\"genre_ids\":[53,28,18],\"id\":793723,\"original_language\":\"fr\",\"original_title\":\"Sentinelle\",\"overview\":\"Transferred home after a traumatizing combat mission, a highly trained French soldier uses her lethal skills to hunt down the man who hurt her sister.\",\"popularity\":439.55,\"poster_path\":\"/AmUGn1rJ9XDDP6DYn9OA2uV8MIg.jpg\",\"release_date\":\"2021-03-05\",\"title\":\"Sentinelle\",\"video\":false,\"vote_average\":5.9,\"vote_count\":384}," +
            "{\"adult\":false,\"backdrop_path\":\"/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg\",\"genre_ids\":[28,12,53],\"id\":581387,\"original_language\":\"ko\",\"original_title\":\"백두산\",\"overview\":\"A group of unlikely heroes from across the Korean peninsula try to save the day after a volcano erupts on the mythical and majestic Baekdu Mountain.\",\"popularity\":486.039,\"poster_path\":\"/zoeKREZ2IdAUnXISYCS0E6H5BVh.jpg\",\"release_date\":\"2019-12-19\",\"title\":\"Ashfall\",\"video\":false,\"vote_average\":6.4,\"vote_count\":256}," +
            "{\"adult\":false,\"backdrop_path\":\"/czHYg6LQ5926OL8wj5kC09pNR12.jpg\",\"genre_ids\":[27,35],\"id\":647302,\"original_language\":\"en\",\"original_title\":\"Benny Loves You\",\"overview\":\"Jack, a man desperate to improve his life throws away his beloved childhood plush, Benny. It’s a move that has disastrous consequences when Benny springs to life with deadly intentions!\",\"popularity\":488.11,\"poster_path\":\"/3RE9DNBCvuso5OPZPg71ryntNjx.jpg\",\"release_date\":\"2021-05-07\",\"title\":\"Benny Loves You\",\"video\":false,\"vote_average\":6.3,\"vote_count\":12}],\"total_pages\":500,\"total_results\":10000}"

    const val stringListSeriesResponse = "{\"page\":1,\"results\":[" +
            "{\"backdrop_path\":\"/b0WmHGc8LHTdGCVzxRb3IBMur57.jpg\",\"first_air_date\":\"2021-03-19\",\"genre_ids\":[10765,10759,18,10768],\"id\":88396,\"name\":\"The Falcon and the Winter Soldier\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Falcon and the Winter Soldier\",\"overview\":\"Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.\",\"popularity\":1143.513,\"poster_path\":\"/6kbAMLteGO8yyewYau6bJ683sw7.jpg\",\"vote_average\":7.9,\"vote_count\":5526}," +
            "{\"backdrop_path\":\"/jeruqNWhqRqOR1QyqdQdHunrvU5.jpg\",\"first_air_date\":\"2014-10-07\",\"genre_ids\":[18,10765],\"id\":60735,\"name\":\"The Flash\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Flash\",\"overview\":\"After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \\\"meta-human\\\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.\",\"popularity\":997.45,\"poster_path\":\"/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg\",\"vote_average\":7.7,\"vote_count\":7615}," +
            "{\"backdrop_path\":\"/mZjZgY6ObiKtVuKVDrnS9VnuNlE.jpg\",\"first_air_date\":\"2017-09-25\",\"genre_ids\":[18],\"id\":71712,\"name\":\"The Good Doctor\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Good Doctor\",\"overview\":\"A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives\",\"popularity\":969.886,\"poster_path\":\"/6tfT03sGp9k4c0J3dypjrI8TSAI.jpg\",\"vote_average\":8.6,\"vote_count\":8386}," +
            "{\"backdrop_path\":\"/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg\",\"first_air_date\":\"2021-03-26\",\"genre_ids\":[16,10759,18,10765],\"id\":95557,\"name\":\"Invincible\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Invincible\",\"overview\":\"Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.\",\"popularity\":922.578,\"poster_path\":\"/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg\",\"vote_average\":8.9,\"vote_count\":1659}," +
            "{\"backdrop_path\":\"/4YKkS95v9o9c0tBVA46xIn6M1tx.jpg\",\"first_air_date\":\"2021-05-07\",\"genre_ids\":[10765,10759,18],\"id\":93484,\"name\":\"Jupiter's Legacy\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Jupiter's Legacy\",\"overview\":\"When the world's first generation of superheroes received their powers in the 1930s become the revered elder guard in the present, their superpowered children struggle to live up to the legendary feats of their parents.\",\"popularity\":873.987,\"poster_path\":\"/9yxep7oJdkj3Pla9TD9gKflRApY.jpg\",\"vote_average\":7.4,\"vote_count\":196}," +
            "{\"backdrop_path\":\"/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg\",\"first_air_date\":\"2005-03-27\",\"genre_ids\":[18],\"id\":1416,\"name\":\"Grey's Anatomy\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Grey's Anatomy\",\"overview\":\"Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.\",\"popularity\":719.896,\"poster_path\":\"/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg\",\"vote_average\":8.2,\"vote_count\":6048}," +
            "{\"backdrop_path\":\"/ta5oblpMlEcIPIS2YGcq9XEkWK2.jpg\",\"first_air_date\":\"2016-01-25\",\"genre_ids\":[80,10765],\"id\":63174,\"name\":\"Lucifer\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Lucifer\",\"overview\":\"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.\",\"popularity\":653.802,\"poster_path\":\"/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg\",\"vote_average\":8.5,\"vote_count\":8585}," +
            "{\"backdrop_path\":\"/sjxtIUCWR74yPPcZFfTsToepfWm.jpg\",\"first_air_date\":\"2021-05-04\",\"genre_ids\":[10765,10759,16],\"id\":105971,\"name\":\"The Bad Batch\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Bad Batch\",\"overview\":\"Follow the elite and experimental Clones of the Bad Batch as they find their way in a rapidly changing galaxy in the aftermath of the Clone Wars.\",\"popularity\":651.924,\"poster_path\":\"/WjQmEWFrOf98nT5aEfUfVYz9N2.jpg\",\"vote_average\":8.9,\"vote_count\":170}," +
            "{\"backdrop_path\":\"/wkyzeBBKLhSg1Oqhky5yoiFF2hG.jpg\",\"first_air_date\":\"2018-04-22\",\"genre_ids\":[18],\"id\":79008,\"name\":\"Luis Miguel: The Series\",\"origin_country\":[\"MX\"],\"original_language\":\"es\",\"original_name\":\"Luis Miguel: La Serie\",\"overview\":\"The series dramatizes the life story of Mexican superstar singer Luis Miguel, who has captivated audiences in Latin America and beyond for decades.\",\"popularity\":645.799,\"poster_path\":\"/34FaY8qpjBAVysSfrJ1l7nrAQaD.jpg\",\"vote_average\":8.1,\"vote_count\":406}," +
            "{\"backdrop_path\":\"/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg\",\"first_air_date\":\"2017-01-26\",\"genre_ids\":[9648,18,80],\"id\":69050,\"name\":\"Riverdale\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Riverdale\",\"overview\":\"Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.\",\"popularity\":608.687,\"poster_path\":\"/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg\",\"vote_average\":8.6,\"vote_count\":11258}," +
            "{\"backdrop_path\":\"/5VltHQJXdmbSD6gEJw3R8R1Kbmc.jpg\",\"first_air_date\":\"2016-09-23\",\"genre_ids\":[9648,10765,10759],\"id\":65820,\"name\":\"Van Helsing\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Van Helsing\",\"overview\":\"Vanessa Helsing, the daughter of famous vampire hunter and Dracula nemesis Abraham Van Helsing is resurrected five years in the future to find out that vampires have taken over the world and that she possesses unique power over them. She is humanity’s last hope to lead an offensive to take back what has been lost.\",\"popularity\":590.403,\"poster_path\":\"/qMC4nnMZfnFMVnxRtN4Rey3NDXb.jpg\",\"vote_average\":6.9,\"vote_count\":554}," +
            "{\"backdrop_path\":\"/suopoADq0k8YZr4dQXcU6pToj6s.jpg\",\"first_air_date\":\"2011-04-17\",\"genre_ids\":[10765,18,10759],\"id\":1399,\"name\":\"Game of Thrones\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Game of Thrones\",\"overview\":\"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.\",\"popularity\":487.928,\"poster_path\":\"/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg\",\"vote_average\":8.4,\"vote_count\":14389}," +
            "{\"backdrop_path\":\"/58PON1OrnBiX6CqEHgeWKVwrCn6.jpg\",\"first_air_date\":\"2015-08-23\",\"genre_ids\":[10759,18],\"id\":62286,\"name\":\"Fear the Walking Dead\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Fear the Walking Dead\",\"overview\":\"What did the world look like as it was transforming into the horrifying apocalypse depicted in \\\"The Walking Dead\\\"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.\",\"popularity\":474.013,\"poster_path\":\"/4UjiPdFKJGJYdxwRs2Rzg7EmWqr.jpg\",\"vote_average\":7.6,\"vote_count\":3519}," +
            "{\"backdrop_path\":\"/hNiGqLsiD30C194lci7VYDmciHD.jpg\",\"first_air_date\":\"2017-04-26\",\"genre_ids\":[10765,18],\"id\":69478,\"name\":\"The Handmaid's Tale\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Handmaid's Tale\",\"overview\":\"Set in a dystopian future, a woman is forced to live as a concubine under a fundamentalist theocratic dictatorship. A TV adaptation of Margaret Atwood's novel.\",\"popularity\":459.772,\"poster_path\":\"/oIkxqt6ug5zT5ZSUUyc1Iqopf02.jpg\",\"vote_average\":8.2,\"vote_count\":1332}," +
            "{\"backdrop_path\":\"/Wu8kh7oyvaIfkNyMJyJHCamh5L.jpg\",\"first_air_date\":\"2020-12-04\",\"genre_ids\":[18],\"id\":97180,\"name\":\"Selena: The Series\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Selena: The Series\",\"overview\":\"As Mexican-American Tejano singer Selena comes of age and realizes her dreams, she and her family make tough choices to hold on to love and music.\",\"popularity\":457.525,\"poster_path\":\"/mYsWyfiIMxx4HDm0Wck7oJ9ckez.jpg\",\"vote_average\":7.5,\"vote_count\":1312}," +
            "{\"backdrop_path\":\"/uro2Khv7JxlzXtLb8tCIbRhkb9E.jpg\",\"first_air_date\":\"2010-10-31\",\"genre_ids\":[10759,18,10765],\"id\":1402,\"name\":\"The Walking Dead\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Walking Dead\",\"overview\":\"Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.\",\"popularity\":418.091,\"poster_path\":\"/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg\",\"vote_average\":8.1,\"vote_count\":10798}," +
            "{\"backdrop_path\":\"/1i1N0AVRb54H6ZFPDTwbo9MLxSF.jpg\",\"first_air_date\":\"2021-01-15\",\"genre_ids\":[10765,9648,18],\"id\":85271,\"name\":\"WandaVision\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"WandaVision\",\"overview\":\"Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.\",\"popularity\":408.142,\"poster_path\":\"/glKDfE6btIRcVB5zrjspRIs4r52.jpg\",\"vote_average\":8.4,\"vote_count\":8438}," +
            "{\"backdrop_path\":\"/gCblYqt8ctD6aAFnZqLJWKWnjvM.jpg\",\"first_air_date\":\"2020-12-06\",\"genre_ids\":[18],\"id\":86430,\"name\":\"Your Honor\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Your Honor\",\"overview\":\"New Orleans judge Michael Desiato is forced to confront his own deepest convictions when his son is involved in a hit and run that embroils an organized crime family.\",\"popularity\":405.59,\"poster_path\":\"/xWJZjIKPeEZhK3JRYKOe06yW6IU.jpg\",\"vote_average\":8.2,\"vote_count\":503}," +
            "{\"backdrop_path\":\"/pLG4ihU1d2XkQbASQDjsFu9U7d9.jpg\",\"first_air_date\":\"2021-03-24\",\"genre_ids\":[18,80,9648],\"id\":120168,\"name\":\"Who Killed Sara?\",\"origin_country\":[\"MX\"],\"original_language\":\"es\",\"original_name\":\"¿Quién mató a Sara?\",\"overview\":\"Hell-bent on exacting revenge and proving he was framed for his sister's murder, Álex sets out to unearth much more than the crime's real culprit.\",\"popularity\":397.662,\"poster_path\":\"/o7uk5ChRt3quPIv8PcvPfzyXdMw.jpg\",\"vote_average\":7.8,\"vote_count\":495}," +
            "{\"backdrop_path\":\"/fRYwdeNjMqC30EhofPx5PlDpdun.jpg\",\"first_air_date\":\"2018-10-25\",\"genre_ids\":[10765,18],\"id\":79460,\"name\":\"Legacies\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Legacies\",\"overview\":\"In a place where young witches, vampires, and werewolves are nurtured to be their best selves in spite of their worst impulses, Klaus Mikaelson’s daughter, 17-year-old Hope Mikaelson, Alaric Saltzman’s twins, Lizzie and Josie Saltzman, among others, come of age into heroes and villains at The Salvatore School for the Young and Gifted.\",\"popularity\":388.79,\"poster_path\":\"/qTZIgXrBKURBK1KrsT7fe3qwtl9.jpg\",\"vote_average\":8.6,\"vote_count\":1865}],\"total_pages\":500,\"total_results\":10000}"

    private const val stringDetailMovieResponse = "{\"adult\":false,\"backdrop_path\":\"/fPGeS6jgdLovQAKunNHX8l0avCy.jpg\",\"belongs_to_collection\":null,\"budget\":0,\"genres\":[{\"id\":28,\"name\":\"Action\"},{\"id\":53,\"name\":\"Thriller\"},{\"id\":10752,\"name\":\"War\"}],\"homepage\":\"https://www.amazon.com/dp/B08VFD1Y3B\",\"id\":567189,\"imdb_id\":\"tt0499097\",\"original_language\":\"en\",\"original_title\":\"Tom Clancy's Without Remorse\",\"overview\":\"An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.\",\"popularity\":3143.69,\"poster_path\":\"/rEm96ib0sPiZBADNKBHKBv5bve9.jpg\",\"production_companies\":[{\"id\":4,\"logo_path\":\"/fycMZt242LVjagMByZOLUGbCvv3.png\",\"name\":\"Paramount\",\"origin_country\":\"US\"},{\"id\":433,\"logo_path\":null,\"name\":\"Weed Road Pictures\",\"origin_country\":\"US\"},{\"id\":82819,\"logo_path\":\"/5Z8WWr0Lf1tInVWwJsxPP0uMz9a.png\",\"name\":\"Skydance Media\",\"origin_country\":\"US\"},{\"id\":51593,\"logo_path\":null,\"name\":\"Midnight Radio\",\"origin_country\":\"US\"},{\"id\":102334,\"logo_path\":\"/espa8KYmHedu5p7GRrP9FFICLUp.png\",\"name\":\"Outlier Society Productions\",\"origin_country\":\"US\"},{\"id\":114732,\"logo_path\":\"/tNCbisMxO5mX2X2bOQxHHQZVYnT.png\",\"name\":\"New Republic Pictures\",\"origin_country\":\"US\"},{\"id\":20580,\"logo_path\":\"/tkFE81jJIqiFYPP8Tho57MXRQEx.png\",\"name\":\"Amazon Studios\",\"origin_country\":\"US\"}],\"production_countries\":[{\"iso_3166_1\":\"US\",\"name\":\"United States of America\"}],\"release_date\":\"2021-04-29\",\"revenue\":0,\"runtime\":109,\"spoken_languages\":[{\"english_name\":\"English\",\"iso_639_1\":\"en\",\"name\":\"English\"}],\"status\":\"Released\",\"tagline\":\"From Tom Clancy, the author of Rainbow Six.\",\"title\":\"Tom Clancy's Without Remorse\",\"video\":false,\"vote_average\":7.3,\"vote_count\":996}"

    private const val stringDetailSeriesResponse = "{\"backdrop_path\":\"/b0WmHGc8LHTdGCVzxRb3IBMur57.jpg\",\"created_by\":[{\"id\":1868712,\"credit_id\":\"605508e2960cde00721fc5e8\",\"name\":\"Malcolm Spellman\",\"gender\":2,\"profile_path\":\"/cNqxh76tysL9D8RcCKR6XqcoyW0.jpg\"}],\"episode_run_time\":[50],\"first_air_date\":\"2021-03-19\",\"genres\":[{\"id\":10765,\"name\":\"Sci-Fi & Fantasy\"},{\"id\":10759,\"name\":\"Action & Adventure\"},{\"id\":18,\"name\":\"Drama\"},{\"id\":10768,\"name\":\"War & Politics\"}],\"homepage\":\"https://www.disneyplus.com/series/the-falcon-and-the-winter-soldier/4gglDBMx8icA\",\"id\":88396,\"in_production\":false,\"languages\":[\"en\"],\"last_air_date\":\"2021-04-23\",\"last_episode_to_air\":{\"air_date\":\"2021-04-23\",\"episode_number\":6,\"id\":2558743,\"name\":\"One World, One People\",\"overview\":\"As The Flag Smashers escalate their efforts, Sam and Bucky take action.\",\"production_code\":\"\",\"season_number\":1,\"still_path\":\"/qXxCqMP7aj3rGndhVfGUyyU6hyq.jpg\",\"vote_average\":7.375,\"vote_count\":8},\"name\":\"The Falcon and the Winter Soldier\",\"next_episode_to_air\":null,\"networks\":[{\"name\":\"Disney+\",\"id\":2739,\"logo_path\":\"/gJ8VX6JSu3ciXHuC2dDGAo2lvwM.png\",\"origin_country\":\"US\"}],\"number_of_episodes\":6,\"number_of_seasons\":1,\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Falcon and the Winter Soldier\",\"overview\":\"Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.\",\"popularity\":1143.513,\"poster_path\":\"/6kbAMLteGO8yyewYau6bJ683sw7.jpg\",\"production_companies\":[{\"id\":420,\"logo_path\":\"/hUzeosd33nzE5MCNsZxCGEKTXaQ.png\",\"name\":\"Marvel Studios\",\"origin_country\":\"US\"}],\"production_countries\":[{\"iso_3166_1\":\"US\",\"name\":\"United States of America\"}],\"seasons\":[{\"air_date\":\"2021-03-19\",\"episode_count\":6,\"id\":156676,\"name\":\"Season 1\",\"overview\":\"\",\"poster_path\":\"/fIT6Y6O3cUX1X8qY8pZgzEvxUDQ.jpg\",\"season_number\":1}],\"spoken_languages\":[{\"english_name\":\"English\",\"iso_639_1\":\"en\",\"name\":\"English\"}],\"status\":\"Ended\",\"tagline\":\"Honor the shield.\",\"type\":\"Miniseries\",\"vote_average\":7.9,\"vote_count\":5620}"

    fun generateMoviesList() : ArrayList<MovieModel>{
        val obj = Gson().fromJson(stringListMovieResponse, DiscoverMovieResponse::class.java)
        return  obj.results
    }

    fun generateSeriesList() : ArrayList<SeriesModel>{
        val obj = Gson().fromJson(stringListSeriesResponse, DiscoverSeriesResponse::class.java)
        return  obj.results
    }

    fun generateMovieEntityList() : List<MovieEntity> {
        val dataMovieModel = generateMoviesList()
        val movieList = ArrayList<MovieEntity>()
        for (response in dataMovieModel){
            val movie = MovieEntity(
                    response.id,
                    response.voteAverage,
                    response.popularity,
                    response.title,
                    response.posterPath,
                    response.originalLanguage,
                    response.originalTitle,
                    response.backdropPath,
                    response.releaseDate,
                    response.overview)
            movieList.add( movie )
        }

        return movieList
    }

    fun generateSeriesEntityList() : List<SeriesEntity> {
        val dataSeriesModel = generateSeriesList()
        val seriesList = ArrayList<SeriesEntity>()
        for (response in dataSeriesModel) {
            val series = SeriesEntity(
                    response.id,
                    response.voteAverage,
                    response.popularity,
                    response.title,
                    response.posterPath,
                    response.originalLanguage,
                    response.originalTitle,
                    response.backdropPath,
                    response.release_date,
                    response.overview
            )
            seriesList.add(series)
        }
        return seriesList
    }

    fun generateDetailMovie() : MovieDetail {
        return Gson().fromJson(stringDetailMovieResponse, MovieDetail::class.java)
    }

    fun generateDetailSeries() : SeriesDetail {
        return Gson().fromJson(stringDetailSeriesResponse, SeriesDetail::class.java)
    }

    fun generateFavEntity(type : String) :FavoriteEntity {
        return if (type == MOVIE_TYPE) {
            val data = generateDetailMovie()
            FavoriteEntity(data.id, data.title, data.posterPath, data.backdropPath, type)
        } else {
            val data = generateDetailSeries()
            FavoriteEntity(data.id, data.name, data.posterPath, data.backdropPath, type)
        }
    }

    fun generateFavEntityList() : List<FavoriteEntity> {
        val data = ArrayList<FavoriteEntity>()
        data.add(generateFavEntity(MOVIE_TYPE))
        data.add(generateFavEntity(SERIES_TYPE))
        return data
    }
}
