package com.faprayyy.tonton.utils

fun getSeriesResponse() : String {

    return "{\"page\":1,\"results\":[" +
            "{\"backdrop_path\":\"/b0WmHGc8LHTdGCVzxRb3IBMur57.jpg\",\"first_air_date\":\"2021-03-19\",\"genre_ids\":[10765,10759,18,10768],\"id\":88396,\"name\":\"The Falcon and the Winter Soldier\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Falcon and the Winter Soldier\",\"overview\":\"Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.\",\"popularity\":5129.317,\"poster_path\":\"/6kbAMLteGO8yyewYau6bJ683sw7.jpg\",\"vote_average\":7.9,\"vote_count\":4830}," +
            "{\"backdrop_path\":\"/mZjZgY6ObiKtVuKVDrnS9VnuNlE.jpg\",\"first_air_date\":\"2017-09-25\",\"genre_ids\":[18],\"id\":71712,\"name\":\"The Good Doctor\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Good Doctor\",\"overview\":\"A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives\",\"popularity\":1722.506,\"poster_path\":\"/6tfT03sGp9k4c0J3dypjrI8TSAI.jpg\",\"vote_average\":8.6,\"vote_count\":8084}," +
            "{\"backdrop_path\":\"/z59kJfcElR9eHO9rJbWp4qWMuee.jpg\",\"first_air_date\":\"2014-10-07\",\"genre_ids\":[18,10765],\"id\":60735,\"name\":\"The Flash\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"The Flash\",\"overview\":\"After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \\\"meta-human\\\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.\",\"popularity\":1352.784,\"poster_path\":\"/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg\",\"vote_average\":7.7,\"vote_count\":7432}," +
            "{\"backdrop_path\":\"/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg\",\"first_air_date\":\"2021-03-26\",\"genre_ids\":[16,10759,18],\"id\":95557,\"name\":\"Invincible\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Invincible\",\"overview\":\"Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.\",\"popularity\":1168.298,\"poster_path\":\"/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg\",\"vote_average\":8.9,\"vote_count\":817}," +
            "{\"backdrop_path\":\"/wkyzeBBKLhSg1Oqhky5yoiFF2hG.jpg\",\"first_air_date\":\"2018-04-22\",\"genre_ids\":[18],\"id\":79008,\"name\":\"Luis Miguel: The Series\",\"origin_country\":[\"MX\"],\"original_language\":\"es\",\"original_name\":\"Luis Miguel: La Serie\",\"overview\":\"The series dramatizes the life story of Mexican superstar singer Luis Miguel, who has captivated audiences in Latin America and beyond for decades.\",\"popularity\":1061.507,\"poster_path\":\"/34FaY8qpjBAVysSfrJ1l7nrAQaD.jpg\",\"vote_average\":7.9,\"vote_count\":287}," +
            "{\"backdrop_path\":\"/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg\",\"first_air_date\":\"2005-03-27\",\"genre_ids\":[18],\"id\":1416,\"name\":\"Grey's Anatomy\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Grey's Anatomy\",\"overview\":\"Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.\",\"popularity\":976.595,\"poster_path\":\"/clnyhPqj1SNgpAdeSS6a6fwE6Bo.jpg\",\"vote_average\":8.2,\"vote_count\":5916}," +
            "{\"backdrop_path\":\"/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg\",\"first_air_date\":\"2017-01-26\",\"genre_ids\":[9648,18,80],\"id\":69050,\"name\":\"Riverdale\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Riverdale\",\"overview\":\"Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.\",\"popularity\":888.565,\"poster_path\":\"/wRbjVBdDo5qHAEOVYoMWpM58FSA.jpg\",\"vote_average\":8.6,\"vote_count\":11080}," +
            "{\"backdrop_path\":\"/57vVjteucIF3bGnZj6PmaoJRScw.jpg\",\"first_air_date\":\"2021-01-15\",\"genre_ids\":[10765,9648,18],\"id\":85271,\"name\":\"WandaVision\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"WandaVision\",\"overview\":\"Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.\",\"popularity\":785.672,\"poster_path\":\"/glKDfE6btIRcVB5zrjspRIs4r52.jpg\",\"vote_average\":8.4,\"vote_count\":8253}," +
            "{\"backdrop_path\":\"/ta5oblpMlEcIPIS2YGcq9XEkWK2.jpg\",\"first_air_date\":\"2016-01-25\",\"genre_ids\":[80,10765],\"id\":63174,\"name\":\"Lucifer\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Lucifer\",\"overview\":\"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.\",\"popularity\":782.351,\"poster_path\":\"/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg\",\"vote_average\":8.5,\"vote_count\":8344}," +
            "{\"backdrop_path\":\"/5VltHQJXdmbSD6gEJw3R8R1Kbmc.jpg\",\"first_air_date\":\"2016-09-23\",\"genre_ids\":[9648,10765,10759],\"id\":65820,\"name\":\"Van Helsing\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Van Helsing\",\"overview\":\"Vanessa Helsing, the daughter of famous vampire hunter and Dracula nemesis Abraham Van Helsing is resurrected five years in the future to find out that vampires have taken over the world and that she possesses unique power over them. She is humanity’s last hope to lead an offensive to take back what has been lost.\",\"popularity\":703.989,\"poster_path\":\"/r8ODGmfNbZQlNhiJl2xQENE2jsk.jpg\",\"vote_average\":6.9,\"vote_count\":516}," +
            "{\"backdrop_path\":\"/wgEWTYAAY7F04o4F20j0L1DGB8i.jpg\",\"first_air_date\":\"2019-07-23\",\"genre_ids\":[18],\"id\":91605,\"name\":\"I Am...\",\"origin_country\":[],\"original_language\":\"en\",\"original_name\":\"I Am...\",\"overview\":\"Each hour-long film follows a different women as they experience “moments that are emotionally raw, thought-provoking and utterly personal”.\",\"popularity\":446.042,\"poster_path\":\"/oogunE22HDTcTxFakKQbwqfw1qo.jpg\",\"vote_average\":5.4,\"vote_count\":18}," +
            "{\"backdrop_path\":\"/fRYwdeNjMqC30EhofPx5PlDpdun.jpg\",\"first_air_date\":\"2018-10-25\",\"genre_ids\":[10765,18],\"id\":79460,\"name\":\"Legacies\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Legacies\",\"overview\":\"In a place where young witches, vampires, and werewolves are nurtured to be their best selves in spite of their worst impulses, Klaus Mikaelson’s daughter, 17-year-old Hope Mikaelson, Alaric Saltzman’s twins, Lizzie and Josie Saltzman, among others, come of age into heroes and villains at The Salvatore School for the Young and Gifted.\",\"popularity\":431.632,\"poster_path\":\"/qTZIgXrBKURBK1KrsT7fe3qwtl9.jpg\",\"vote_average\":8.6,\"vote_count\":1806}," +
            "{\"backdrop_path\":\"/wAEWZm2pSopAbqE5dQWE0ET8aR5.jpg\",\"first_air_date\":\"2021-01-08\",\"genre_ids\":[99],\"id\":114695,\"name\":\"Marvel Studios: Legends\",\"origin_country\":[\"US\"],\"original_language\":\"en\",\"original_name\":\"Marvel Studios: Legends\",\"overview\":\"Revisit the epic heroes, villains and moments from across the MCU in preparation for the stories still to come. Each dynamic segment feeds directly into the upcoming series — setting the stage for future events. This series weaves together the many threads that constitute the unparalleled Marvel Cinematic Universe.\",\"popularity\":417.937,\"poster_path\":\"/EpDuYIK81YtCUT3gH2JDpyj8Qk.jpg\",\"vote_average\":7.7,\"vote_count\":385}," +
            "{\"backdrop_path\":\"/aq2yEMgRQBPfRkrO0Repo2qhUAT.jpg\",\"first_air_date\":\"2013-03-03\",\"genre_ids\":[10759,18],\"id\":44217,\"name\":\"Vikings\",\"origin_country\":[\"CA\"],\"original_language\":\"en\",\"original_name\":\"Vikings\",\"overview\":\"The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.\",\"popularity\":413.69,\"poster_path\":\"/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg\",\"vote_average\":8,\"vote_count\":4382}," +
            "{\"backdrop_path\":\"/9RqliZcoDEjSEISeA0LY9meAiNv.jpg\",\"first_air_date\":\"2015-10-19\",\"genre_ids\":[10759,16,10762],\"id\":65334,\"name\":\"Miraculous: Tales of Ladybug & Cat Noir\",\"origin_country\":[\"FR\"],\"original_language\":\"fr\",\"original_name\":\"Miraculous, les aventures de Ladybug et Chat Noir\",\"overview\":\"Normal high school kids by day, protectors of Paris by night! Miraculous follows the heroic adventures of Marinette and Adrien as they transform into Ladybug and Cat Noir and set out to capture akumas, creatures responsible for turning the people of Paris into villains. But neither hero knows the other’s true identity – or that they’re classmates!\",\"popularity\":409.207,\"poster_path\":\"/qxbW47zmgFyBVmZSIqD9NA1DEjT.jpg\",\"vote_average\":7.9,\"vote_count\":2467}],\"total_pages\":500,\"total_results\":10000}"
}